export type TStorageKey =
  | 'algorithm'
  | 'authorNoteCSS'
  | 'authorNoteHTML'
  | 'authorNoteJS'
  | 'authorNoteSlateValue'
  | 'classID'
  | 'codeEditorPlacement'
  | 'documentName'
  | 'extensionURL'
  | 'feedbackCSS'
  | 'feedbackHTML'
  | 'feedbackJS'
  | 'feedbackSlateValue'
  | 'hash'
  | 'permission'
  | 'questionCSS'
  | 'questionHTML'
  | 'questionJS'
  | 'questionSlateValue'
  | 'securityToken'
  | 'theme'
  | 'username'
  | 'uuid'
  | 'withModernUI'
type _TStorage = { [key in TStorageKey]: string }
export type TStorage = _TStorage & {
  codeEditorPlacement: 'bottom' | 'left' | 'right' | 'top'
  theme: 'dark' | 'light'
  withModernUI: 'false' | 'true'
}
